name: designs
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bottomreveal: ^2.0.0
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.5
  font_awesome_flutter: ^10.3.0
  image_picker: ^0.8.6+1
  path_provider: ^2.0.12
  toggle_switch: ^2.0.1
  url_launcher: ^6.1.8
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  google_sign_in: ^5.4.4
  shared_preferences: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
